// Competition(League)
export const GET_COMPETITION_LIST = 'GET_COMPETITION_LIST';
export const GET_COMPETITION_LIST_SUCCESS = 'GET_COMPETITION_LIST_SUCCESS';
export const GET_COMPETITION_LIST_ERROR = 'GET_COMPETITION_LIST_ERROR';

export const UPDATE_TEAMS_PLAYERS = 'UPDATE_TEAMS_PLAYERS';
export const UPDATE_TEAMS_PLAYERS_SUCCESS = 'UPDATE_TEAMS_PLAYERS_SUCCESS';
export const UPDATE_TEAMS_PLAYERS_ERROR = 'UPDATE_TEAMS_PLAYERS_ERROR';
