const competitions = [
  {
    id: 2006,
    area: {
      id: 2001,
      name: 'Africa',
      countryCode: 'AFR',
      ensignUrl: null,
    },
    name: 'WC Qualification',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 555,
      startDate: '2019-09-04',
      endDate: '2021-11-16',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2018-06-04T23:54:04Z',
  },
  {
    id: 2023,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: null,
    },
    name: 'Primera B Nacional',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 547,
      startDate: '2019-08-16',
      endDate: '2020-06-14',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:44:34Z',
  },
  {
    id: 2024,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: null,
    },
    name: 'Superliga Argentina',
    code: 'ASL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 539,
      startDate: '2019-07-27',
      endDate: '2020-03-01',
      currentMatchday: 22,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:44:41Z',
  },
  {
    id: 2025,
    area: {
      id: 2011,
      name: 'Argentina',
      countryCode: 'ARG',
      ensignUrl: null,
    },
    name: 'Supercopa Argentina',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 430,
      startDate: '2019-04-04',
      endDate: '2019-04-04',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2019-05-03T05:08:18Z',
  },
  {
    id: 2147,
    area: {
      id: 2014,
      name: 'Asia',
      countryCode: 'ASI',
      ensignUrl: null,
    },
    name: 'WC Qualification',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 465,
      startDate: '2019-06-06',
      endDate: '2021-11-16',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2020-06-03T00:00:01Z',
  },
  {
    id: 2008,
    area: {
      id: 2015,
      name: 'Australia',
      countryCode: 'AUS',
      ensignUrl: null,
    },
    name: 'A League',
    code: 'AAL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 548,
      startDate: '2019-10-11',
      endDate: '2020-08-19',
      currentMatchday: 27,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:45:20Z',
  },
  {
    id: 2026,
    area: {
      id: 2015,
      name: 'Australia',
      countryCode: 'AUS',
      ensignUrl: null,
    },
    name: 'FFA Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 592,
      startDate: '2020-02-19',
      endDate: '2020-10-28',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-10-23T23:59:22Z',
  },
  {
    id: 2020,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    },
    name: 'Erste Liga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 626,
      startDate: '2020-09-11',
      endDate: '2021-05-21',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T05:59:29Z',
  },
  {
    id: 2012,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    },
    name: 'Bundesliga',
    code: 'ABL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 620,
      startDate: '2020-09-11',
      endDate: '2021-05-31',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T02:55:57Z',
  },
  {
    id: 2022,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    },
    name: 'Playoffs 1/2',
    code: 'APL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 24,
      startDate: '2018-05-31',
      endDate: '2018-06-03',
      currentMatchday: null,
      winner: {
        id: 2022,
        name: 'spusu SKN St. Pölten',
        shortName: 'St. Pölten',
        tla: 'STP',
        crestUrl: 'https://crests.football-data.org/2022.svg',
      },
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-08-23T15:47:33Z',
  },
  {
    id: 2027,
    area: {
      id: 2016,
      name: 'Austria',
      countryCode: 'AUT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
    },
    name: 'ÖFB Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 627,
      startDate: '2020-08-28',
      endDate: '2021-05-01',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-09-30T21:23:15Z',
  },
  {
    id: 2028,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    },
    name: 'Coupe de Belgique',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 535,
      startDate: '2019-07-28',
      endDate: '2020-05-31',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:46:14Z',
  },
  {
    id: 2033,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    },
    name: 'Division 1B',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 610,
      startDate: '2020-08-21',
      endDate: '2021-05-31',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T13:40:01Z',
  },
  {
    id: 2009,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    },
    name: 'Jupiler Pro League',
    code: 'BJL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 609,
      startDate: '2020-08-08',
      endDate: '2021-05-31',
      currentMatchday: 8,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T00:11:51Z',
  },
  {
    id: 2032,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    },
    name: 'Playoffs II',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 34,
      startDate: '2018-03-31',
      endDate: '2018-05-23',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-02T13:08:02Z',
  },
  {
    id: 2010,
    area: {
      id: 2023,
      name: 'Belgium',
      countryCode: 'BEL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
    },
    name: 'Supercoupe de Belgique',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 536,
      startDate: '2019-07-20',
      endDate: '2019-07-20',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-07-21T23:00:07Z',
  },
  {
    id: 2034,
    area: {
      id: 2028,
      name: 'Bolivia',
      countryCode: 'BOL',
      ensignUrl: null,
    },
    name: 'LFPB',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 556,
      startDate: '2020-01-21',
      endDate: '2020-11-28',
      currentMatchday: 26,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-05-26T00:00:00Z',
  },
  {
    id: 2035,
    area: {
      id: 2030,
      name: 'Bosnia and Herzegovina',
      countryCode: 'BIH',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg',
    },
    name: 'Premier Liga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 598,
      startDate: '2020-08-01',
      endDate: '2021-05-30',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T16:19:33Z',
  },
  {
    id: 2037,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: null,
    },
    name: 'Copa do Brasil',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 557,
      startDate: '2020-02-05',
      endDate: '2020-09-16',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-25T04:25:56Z',
  },
  {
    id: 2038,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: null,
    },
    name: 'Série D',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 595,
      startDate: '2020-05-17',
      endDate: '2020-11-22',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T15:15:02Z',
  },
  {
    id: 2036,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: null,
    },
    name: 'Série C',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 594,
      startDate: '2020-05-02',
      endDate: '2020-10-31',
      currentMatchday: 9,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:31Z',
  },
  {
    id: 2029,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: null,
    },
    name: 'Série B',
    code: 'BSB',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 593,
      startDate: '2020-05-01',
      endDate: '2020-11-28',
      currentMatchday: 14,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:00:18Z',
  },
  {
    id: 2013,
    area: {
      id: 2032,
      name: 'Brazil',
      countryCode: 'BRA',
      ensignUrl: null,
    },
    name: 'Série A',
    code: 'BSA',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 589,
      startDate: '2020-08-09',
      endDate: '2021-02-24',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T15:18:13Z',
  },
  {
    id: 2039,
    area: {
      id: 2035,
      name: 'Bulgaria',
      countryCode: 'BGR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg',
    },
    name: 'Kupa na Bulgarija',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 639,
      startDate: '2020-09-08',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-01T21:40:04Z',
  },
  {
    id: 2040,
    area: {
      id: 2035,
      name: 'Bulgaria',
      countryCode: 'BGR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg',
    },
    name: 'A PFG',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 611,
      startDate: '2020-08-08',
      endDate: '2021-05-30',
      currentMatchday: 8,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-04T21:17:10Z',
  },
  {
    id: 2041,
    area: {
      id: 2040,
      name: 'Canada',
      countryCode: 'CAN',
      ensignUrl: null,
    },
    name: 'Canadian Championship',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 558,
      startDate: '2020-06-16',
      endDate: '2020-09-24',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:48:36Z',
  },
  {
    id: 2042,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 44,
      startDate: '2017-11-25',
      endDate: '2017-12-21',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:01:23Z',
  },
  {
    id: 2043,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Supercopa de Chile',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 435,
      startDate: '2019-03-23',
      endDate: '2019-03-23',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-03-24T20:10:07Z',
  },
  {
    id: 2048,
    area: {
      id: 2045,
      name: 'Chile',
      countryCode: 'CHL',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: 'CPD',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 560,
      startDate: '2020-01-24',
      endDate: '2020-11-28',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T04:14:47Z',
  },
  {
    id: 2044,
    area: {
      id: 2046,
      name: 'China PR',
      countryCode: 'CHN',
      ensignUrl: null,
    },
    name: 'Chinese Super League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 587,
      startDate: '2020-02-22',
      endDate: '2020-10-31',
      currentMatchday: 14,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-28T22:16:56Z',
  },
  {
    id: 2045,
    area: {
      id: 2049,
      name: 'Colombia',
      countryCode: 'COL',
      ensignUrl: null,
    },
    name: 'Liga Postobón',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 559,
      startDate: '2020-01-25',
      endDate: '2020-12-06',
      currentMatchday: 12,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T06:09:56Z',
  },
  {
    id: 2046,
    area: {
      id: 2049,
      name: 'Colombia',
      countryCode: 'COL',
      ensignUrl: null,
    },
    name: 'Superliga de Colombia',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 438,
      startDate: '2019-01-24',
      endDate: '2019-01-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2018-06-05T00:02:32Z',
  },
  {
    id: 2047,
    area: {
      id: 2058,
      name: 'Croatia',
      countryCode: 'HRV',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg',
    },
    name: 'Prva Liga',
    code: 'PRVA',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 621,
      startDate: '2020-08-15',
      endDate: '2021-05-30',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T16:15:04Z',
  },
  {
    id: 2049,
    area: {
      id: 2062,
      name: 'Czech Republic',
      countryCode: 'CZE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg',
    },
    name: 'Synot Liga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 612,
      startDate: '2020-08-22',
      endDate: '2021-05-30',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T05:59:33Z',
  },
  {
    id: 2051,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg',
    },
    name: 'DBU Pokalen',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 640,
      startDate: '2020-09-01',
      endDate: '2021-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T05:00:20Z',
  },
  {
    id: 2050,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg',
    },
    name: 'Superliga',
    code: 'DSU',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 622,
      startDate: '2020-09-11',
      endDate: '2021-05-30',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T03:46:04Z',
  },
  {
    id: 2141,
    area: {
      id: 2065,
      name: 'Denmark',
      countryCode: 'DNK',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg',
    },
    name: 'Play Offs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: null,
    numberOfAvailableSeasons: 0,
    lastUpdated: '2018-07-13T13:34:22Z',
  },
  {
    id: 2052,
    area: {
      id: 2069,
      name: 'Ecuador',
      countryCode: 'ECU',
      ensignUrl: null,
    },
    name: 'Copa Pilsener Serie A',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 561,
      startDate: '2020-02-16',
      endDate: '2020-12-19',
      currentMatchday: 15,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T04:30:59Z',
  },
  {
    id: 2139,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'Football League Cup',
    code: 'FLC',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 623,
      startDate: '2020-09-05',
      endDate: '2021-02-28',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-02T01:30:03Z',
  },
  {
    id: 2056,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'FA Community Shield',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 613,
      startDate: '2020-08-29',
      endDate: '2020-08-29',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-09-07T20:57:30Z',
  },
  {
    id: 2055,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'FA Cup',
    code: 'FAC',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 641,
      startDate: '2020-09-01',
      endDate: '2021-05-15',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-04T20:48:58Z',
  },
  {
    id: 2053,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'National League',
    code: 'ENL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 650,
      startDate: '2020-10-02',
      endDate: '2021-06-13',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T05:00:20Z',
  },
  {
    id: 2054,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'League Two',
    code: 'EL2',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 630,
      startDate: '2020-09-12',
      endDate: '2021-06-29',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-04T07:01:26Z',
  },
  {
    id: 2030,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'League One',
    code: 'EL1',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 629,
      startDate: '2020-09-12',
      endDate: '2021-07-13',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 12,
    lastUpdated: '2020-10-03T19:36:08Z',
  },
  {
    id: 2016,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'Championship',
    code: 'ELC',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 628,
      startDate: '2020-09-12',
      endDate: '2021-08-04',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T02:38:45Z',
  },
  {
    id: 2021,
    area: {
      id: 2072,
      name: 'England',
      countryCode: 'ENG',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'Premier League',
    code: 'PL',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 619,
      startDate: '2020-09-12',
      endDate: '2021-05-23',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 28,
    lastUpdated: '2020-10-05T03:50:57Z',
  },
  {
    id: 2057,
    area: {
      id: 2075,
      name: 'Estonia',
      countryCode: 'EST',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg',
    },
    name: 'Meistriliiga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 586,
      startDate: '2020-03-06',
      endDate: '2020-11-07',
      currentMatchday: 23,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:34Z',
  },
  {
    id: 2146,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: null,
    },
    name: 'UEFA Europa League',
    code: 'EL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 631,
      startDate: '2020-08-18',
      endDate: '2021-05-26',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-02T11:00:04Z',
  },
  {
    id: 2001,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: null,
    },
    name: 'UEFA Champions League',
    code: 'CL',
    emblemUrl:
      'https://upload.wikimedia.org/wikipedia/en/b/bf/UEFA_Champions_League_logo_2.svg',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 642,
      startDate: '2020-08-08',
      endDate: '2021-05-29',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 20,
    lastUpdated: '2020-10-01T04:50:03Z',
  },
  {
    id: 2018,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: null,
    },
    name: 'European Championship',
    code: 'EC',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 507,
      startDate: '2020-06-12',
      endDate: '2020-07-12',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2020-09-10T13:51:03Z',
  },
  {
    id: 2058,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: null,
    },
    name: "UEFA Women's EURO",
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 62,
      startDate: '2017-07-16',
      endDate: '2017-08-06',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2020-09-07T20:55:12Z',
  },
  {
    id: 2007,
    area: {
      id: 2077,
      name: 'Europe',
      countryCode: 'EUR',
      ensignUrl: null,
    },
    name: 'WC Qualification',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 8,
      startDate: '2016-09-04',
      endDate: '2017-11-14',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:06:41Z',
  },
  {
    id: 2059,
    area: {
      id: 2080,
      name: 'Finland',
      countryCode: 'FIN',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg',
    },
    name: 'Suomen Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 562,
      startDate: '2020-01-25',
      endDate: '2020-10-03',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-03T21:02:45Z',
  },
  {
    id: 2031,
    area: {
      id: 2080,
      name: 'Finland',
      countryCode: 'FIN',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg',
    },
    name: 'Veikkausliiga',
    code: 'VEI',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 591,
      startDate: '2020-04-11',
      endDate: '2020-11-28',
      currentMatchday: 18,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T16:19:33Z',
  },
  {
    id: 2135,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Coupe de la Ligue',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 522,
      startDate: '2019-08-13',
      endDate: '2020-04-04',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:52:55Z',
  },
  {
    id: 2142,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Ligue 2',
    code: 'FL2',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 597,
      startDate: '2020-08-22',
      endDate: '2021-05-15',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 23,
    lastUpdated: '2020-10-04T09:28:00Z',
  },
  {
    id: 2015,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Ligue 1',
    code: 'FL1',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 596,
      startDate: '2020-08-22',
      endDate: '2021-05-23',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 10,
    lastUpdated: '2020-10-05T04:08:39Z',
  },
  {
    id: 2136,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Trophée des Champions',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 466,
      startDate: '2019-08-03',
      endDate: '2019-08-03',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-08-04T05:45:13Z',
  },
  {
    id: 2143,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 211,
      startDate: '2018-05-23',
      endDate: '2018-05-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-07-12T14:32:17Z',
  },
  {
    id: 2144,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 212,
      startDate: '2018-05-22',
      endDate: '2018-05-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-09-25T15:07:37Z',
  },
  {
    id: 2138,
    area: {
      id: 2081,
      name: 'France',
      countryCode: 'FRA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg',
    },
    name: 'Coupe de France',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 563,
      startDate: '2019-11-06',
      endDate: '2020-04-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-07-25T20:40:00Z',
  },
  {
    id: 2011,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: 'DFB-Pokal',
    code: 'DFB',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 604,
      startDate: '2020-09-11',
      endDate: '2021-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-09-14T23:59:37Z',
  },
  {
    id: 2129,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: 'Regionalliga',
    code: 'REG',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 602,
      startDate: '2020-08-15',
      endDate: '2021-06-05',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T06:35:07Z',
  },
  {
    id: 2140,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: '3. Liga',
    code: 'BL3',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 601,
      startDate: '2020-09-18',
      endDate: '2021-05-22',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 9,
    lastUpdated: '2020-10-05T00:34:38Z',
  },
  {
    id: 2004,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: '2. Bundesliga',
    code: 'BL2',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 600,
      startDate: '2020-09-18',
      endDate: '2021-05-23',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 25,
    lastUpdated: '2020-10-05T00:15:06Z',
  },
  {
    id: 2002,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: 'Bundesliga',
    code: 'BL1',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 599,
      startDate: '2020-09-18',
      endDate: '2021-05-15',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 25,
    lastUpdated: '2020-10-05T03:17:58Z',
  },
  {
    id: 2133,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: 'Frauen Bundesliga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 142,
      startDate: '2017-09-02',
      endDate: '2018-06-03',
      currentMatchday: 22,
      winner: {
        id: 7522,
        name: 'VfL Wolfsburg',
        shortName: null,
        tla: null,
        crestUrl: null,
      },
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:09:39Z',
  },
  {
    id: 2134,
    area: {
      id: 2088,
      name: 'Germany',
      countryCode: 'DEU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
    },
    name: 'DFL Super Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 605,
      startDate: '2020-09-30',
      endDate: '2020-09-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-01T16:15:04Z',
  },
  {
    id: 2131,
    area: {
      id: 2093,
      name: 'Greece',
      countryCode: 'GRC',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg',
    },
    name: 'Greek Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 552,
      startDate: '2019-08-25',
      endDate: '2020-05-23',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-12T21:57:05Z',
  },
  {
    id: 2132,
    area: {
      id: 2093,
      name: 'Greece',
      countryCode: 'GRC',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg',
    },
    name: 'Super League',
    code: 'GSL',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 532,
      startDate: '2019-08-24',
      endDate: '2020-05-30',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:55:11Z',
  },
  {
    id: 2130,
    area: {
      id: 2106,
      name: 'Hungary',
      countryCode: 'HUN',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg',
    },
    name: 'Magyar Kupa',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 564,
      startDate: '2019-09-21',
      endDate: '2020-05-20',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:55:24Z',
  },
  {
    id: 2128,
    area: {
      id: 2106,
      name: 'Hungary',
      countryCode: 'HUN',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg',
    },
    name: 'NB I',
    code: 'HNB',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 614,
      startDate: '2020-08-14',
      endDate: '2021-05-15',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T16:15:08Z',
  },
  {
    id: 2127,
    area: {
      id: 2107,
      name: 'Iceland',
      countryCode: 'ISL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg',
    },
    name: 'Úrvalsdeild',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 585,
      startDate: '2020-04-22',
      endDate: '2020-09-26',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T04:13:43Z',
  },
  {
    id: 2126,
    area: {
      id: 2108,
      name: 'India',
      countryCode: 'IND',
      ensignUrl: null,
    },
    name: 'I-League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 584,
      startDate: '2019-11-30',
      endDate: '2020-04-12',
      currentMatchday: 22,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:55:39Z',
  },
  {
    id: 2125,
    area: {
      id: 2113,
      name: 'Israel',
      countryCode: 'ISR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg',
    },
    name: "Ligat ha'Al",
    code: 'ILH',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 632,
      startDate: '2020-08-29',
      endDate: '2021-05-22',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-02T00:00:27Z',
  },
  {
    id: 2124,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
    },
    name: 'Supercoppa',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 565,
      startDate: '2019-12-22',
      endDate: '2019-12-22',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T12:14:03Z',
  },
  {
    id: 2122,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
    },
    name: 'Coppa Italia',
    code: 'CIT',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 549,
      startDate: '2019-08-03',
      endDate: '2020-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T12:13:56Z',
  },
  {
    id: 2123,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
    },
    name: 'Serie C',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 550,
      startDate: '2019-08-24',
      endDate: '2020-07-05',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T12:13:47Z',
  },
  {
    id: 2121,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
    },
    name: 'Serie B',
    code: 'SB',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 649,
      startDate: '2020-09-26',
      endDate: '2021-06-06',
      currentMatchday: 2,
      winner: null,
    },
    numberOfAvailableSeasons: 16,
    lastUpdated: '2020-10-05T04:09:55Z',
  },
  {
    id: 2019,
    area: {
      id: 2114,
      name: 'Italy',
      countryCode: 'ITA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
    },
    name: 'Serie A',
    code: 'SA',
    emblemUrl: 'https://crests.football-data.org/SA.svg',
    plan: 'TIER_ONE',
    currentSeason: {
      id: 638,
      startDate: '2020-09-20',
      endDate: '2021-05-23',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 16,
    lastUpdated: '2020-10-05T03:18:37Z',
  },
  {
    id: 2118,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: null,
    },
    name: 'J.League Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 581,
      startDate: '2020-02-16',
      endDate: '2020-10-31',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:56:34Z',
  },
  {
    id: 2117,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: null,
    },
    name: 'J. League Division 2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 582,
      startDate: '2020-02-23',
      endDate: '2020-12-20',
      currentMatchday: 24,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:39Z',
  },
  {
    id: 2119,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: null,
    },
    name: 'J. League',
    code: 'JJL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 583,
      startDate: '2020-02-21',
      endDate: '2020-12-19',
      currentMatchday: 20,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-04T19:21:36Z',
  },
  {
    id: 2120,
    area: {
      id: 2116,
      name: 'Japan',
      countryCode: 'JPN',
      ensignUrl: null,
    },
    name: 'Super Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 580,
      startDate: '2020-02-08',
      endDate: '2020-02-08',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-02-09T05:35:08Z',
  },
  {
    id: 2116,
    area: {
      id: 2129,
      name: 'Latvia',
      countryCode: 'LVA',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg',
    },
    name: 'Virslīga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 579,
      startDate: '2020-03-13',
      endDate: '2020-11-14',
      currentMatchday: 21,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:39Z',
  },
  {
    id: 2115,
    area: {
      id: 2135,
      name: 'Lithuania',
      countryCode: 'LTU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg',
    },
    name: 'A Lyga',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 590,
      startDate: '2020-03-06',
      endDate: '2020-11-07',
      currentMatchday: 26,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-04T06:00:42Z',
  },
  {
    id: 2114,
    area: {
      id: 2143,
      name: 'Malta',
      countryCode: 'MLT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg',
    },
    name: 'Premier League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 633,
      startDate: '2020-09-11',
      endDate: '2021-05-30',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-02T11:05:05Z',
  },
  {
    id: 2111,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: null,
    },
    name: 'Copa MX',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 479,
      startDate: '2019-07-30',
      endDate: '2020-04-15',
      currentMatchday: 7,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-15T21:55:07Z',
  },
  {
    id: 2112,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: null,
    },
    name: 'SuperCopa MX',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 480,
      startDate: '2019-07-14',
      endDate: '2019-07-14',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:57:18Z',
  },
  {
    id: 2113,
    area: {
      id: 2149,
      name: 'Mexico',
      countryCode: 'MEX',
      ensignUrl: null,
    },
    name: 'Liga MX',
    code: 'LMX',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 606,
      startDate: '2020-07-24',
      endDate: '2021-05-27',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T08:10:34Z',
  },
  {
    id: 2109,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    },
    name: 'KNVB Beker',
    code: 'KNV',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 538,
      startDate: '2019-08-17',
      endDate: '2020-05-05',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:06:41Z',
  },
  {
    id: 2005,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    },
    name: 'Jupiler League',
    code: 'DJL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 616,
      startDate: '2020-08-28',
      endDate: '2021-05-14',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T16:19:34Z',
  },
  {
    id: 2003,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    },
    name: 'Eredivisie',
    code: 'DED',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 615,
      startDate: '2020-09-12',
      endDate: '2021-05-16',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 11,
    lastUpdated: '2020-10-05T02:54:40Z',
  },
  {
    id: 2110,
    area: {
      id: 2163,
      name: 'Netherlands',
      countryCode: 'NLD',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
    },
    name: 'Johan Cruijff Schaal',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 483,
      startDate: '2019-07-27',
      endDate: '2019-07-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-07-28T00:20:08Z',
  },
  {
    id: 2108,
    area: {
      id: 2171,
      name: 'Northern Ireland',
      countryCode: 'NIR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'League Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 528,
      startDate: '2019-08-10',
      endDate: '2020-02-15',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:06:21Z',
  },
  {
    id: 2107,
    area: {
      id: 2171,
      name: 'Northern Ireland',
      countryCode: 'NIR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    name: 'Premiership',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 496,
      startDate: '2019-08-10',
      endDate: '2020-05-11',
      currentMatchday: 33,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:06:12Z',
  },
  {
    id: 2106,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg',
    },
    name: 'Tippeligaen',
    code: 'TIP',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 577,
      startDate: '2020-04-04',
      endDate: '2020-12-19',
      currentMatchday: 20,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T03:25:58Z',
  },
  {
    id: 2105,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg',
    },
    name: '1. divisjon',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 578,
      startDate: '2020-04-04',
      endDate: '2020-12-07',
      currentMatchday: 19,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:40Z',
  },
  {
    id: 2104,
    area: {
      id: 2173,
      name: 'Norway',
      countryCode: 'NOR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 112,
      startDate: '2017-11-29',
      endDate: '2017-12-02',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:20:23Z',
  },
  {
    id: 2103,
    area: {
      id: 2175,
      name: 'Oceania',
      countryCode: 'OCE',
      ensignUrl: null,
    },
    name: 'WC Qualification',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 111,
      startDate: '2015-08-31',
      endDate: '2017-09-05',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:20:43Z',
  },
  {
    id: 2102,
    area: {
      id: 2181,
      name: 'Panama',
      countryCode: 'PAN',
      ensignUrl: null,
    },
    name: 'Liga Panameña de Fútbol',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 537,
      startDate: '2019-07-28',
      endDate: '2020-06-02',
      currentMatchday: 18,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:05:42Z',
  },
  {
    id: 2101,
    area: {
      id: 2184,
      name: 'Peru',
      countryCode: 'PER',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: 'PPD',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 575,
      startDate: '2020-02-02',
      endDate: '2020-12-12',
      currentMatchday: 16,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T16:19:34Z',
  },
  {
    id: 2099,
    area: {
      id: 2186,
      name: 'Poland',
      countryCode: 'POL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg',
    },
    name: 'Superpuchar Polski',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 607,
      startDate: '2020-08-09',
      endDate: '2020-08-09',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-08-09T20:40:47Z',
  },
  {
    id: 2100,
    area: {
      id: 2186,
      name: 'Poland',
      countryCode: 'POL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg',
    },
    name: 'Puchar Polski',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 643,
      startDate: '2020-08-08',
      endDate: '2021-05-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-09-02T19:47:33Z',
  },
  {
    id: 2098,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'PRT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    },
    name: 'Taça de Portugal',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 554,
      startDate: '2019-09-01',
      endDate: '2020-05-24',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:05:25Z',
  },
  {
    id: 2096,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'PRT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    },
    name: 'Liga2 Cabovisão',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 645,
      startDate: '2020-09-13',
      endDate: '2021-05-19',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T13:50:13Z',
  },
  {
    id: 2017,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'PRT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    },
    name: 'Primeira Liga',
    code: 'PPL',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 644,
      startDate: '2020-09-20',
      endDate: '2021-05-19',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 10,
    lastUpdated: '2020-10-05T04:15:48Z',
  },
  {
    id: 2097,
    area: {
      id: 2187,
      name: 'Portugal',
      countryCode: 'PRT',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
    },
    name: 'Supertaça Cândido de Oliveira',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 485,
      startDate: '2019-08-03',
      endDate: '2019-08-03',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-08-05T22:35:11Z',
  },
  {
    id: 2095,
    area: {
      id: 2192,
      name: 'Republic of Ireland',
      countryCode: 'IRL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg',
    },
    name: 'Premier Division',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 574,
      startDate: '2020-02-14',
      endDate: '2020-10-23',
      currentMatchday: 14,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:41Z',
  },
  {
    id: 2092,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg',
    },
    name: 'Liga II',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 542,
      startDate: '2019-08-02',
      endDate: '2020-05-31',
      currentMatchday: 38,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:04:47Z',
  },
  {
    id: 2094,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg',
    },
    name: 'Liga I',
    code: 'RL1',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 624,
      startDate: '2020-08-21',
      endDate: '2021-05-30',
      currentMatchday: 6,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T03:09:30Z',
  },
  {
    id: 2093,
    area: {
      id: 2194,
      name: 'Romania',
      countryCode: 'ROU',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg',
    },
    name: 'Supercupa României',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 515,
      startDate: '2019-07-13',
      endDate: '2019-07-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-07-07T00:20:01Z',
  },
  {
    id: 2089,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg',
    },
    name: 'Russian Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 646,
      startDate: '2020-08-05',
      endDate: '2021-05-12',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-01T15:45:19Z',
  },
  {
    id: 2088,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg',
    },
    name: 'FNL',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 634,
      startDate: '2020-08-01',
      endDate: '2021-10-03',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T15:40:13Z',
  },
  {
    id: 2137,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg',
    },
    name: 'RFPL',
    code: 'RFPL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 617,
      startDate: '2020-08-09',
      endDate: '2021-05-16',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T03:41:21Z',
  },
  {
    id: 2090,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 96,
      startDate: '2018-05-17',
      endDate: '2018-05-20',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:24:32Z',
  },
  {
    id: 2091,
    area: {
      id: 2195,
      name: 'Russia',
      countryCode: 'RUS',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg',
    },
    name: 'Russian Super Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 647,
      startDate: '2020-08-07',
      endDate: '2020-08-07',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2019-07-07T00:25:01Z',
  },
  {
    id: 2087,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg',
    },
    name: 'Scottish Cup',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 544,
      startDate: '2019-08-10',
      endDate: '2020-05-09',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:04:05Z',
  },
  {
    id: 2085,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg',
    },
    name: 'Championship',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 608,
      startDate: '2020-10-17',
      endDate: '2021-05-30',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-09-10T14:03:59Z',
  },
  {
    id: 2084,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg',
    },
    name: 'Premier League',
    code: 'SPL',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 603,
      startDate: '2020-08-01',
      endDate: '2021-05-30',
      currentMatchday: 10,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T02:39:32Z',
  },
  {
    id: 2086,
    area: {
      id: 2204,
      name: 'Scotland',
      countryCode: 'SCO',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 92,
      startDate: '2018-05-02',
      endDate: '2018-05-13',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:25:54Z',
  },
  {
    id: 2083,
    area: {
      id: 2219,
      name: 'South Africa',
      countryCode: 'RSA',
      ensignUrl: null,
    },
    name: 'ABSA Premiership',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 517,
      startDate: '2019-08-04',
      endDate: '2020-09-05',
      currentMatchday: 30,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:04:13Z',
  },
  {
    id: 2080,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: null,
    },
    name: 'Copa America',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 567,
      startDate: '2020-06-12',
      endDate: '2020-07-12',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:02:11Z',
  },
  {
    id: 2081,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: null,
    },
    name: 'Copa Sudamericana',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 568,
      startDate: '2020-02-04',
      endDate: '2020-11-07',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:02:03Z',
  },
  {
    id: 2082,
    area: {
      id: 2220,
      name: 'South America',
      countryCode: 'SAM',
      ensignUrl: null,
    },
    name: 'WC Qualification',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 524,
      startDate: '2020-03-23',
      endDate: '2021-11-16',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2020-03-30T00:00:05Z',
  },
  {
    id: 2079,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg',
    },
    name: 'Copa del Rey',
    code: 'CDR',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 553,
      startDate: '2019-11-13',
      endDate: '2020-04-18',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:01:55Z',
  },
  {
    id: 2077,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg',
    },
    name: 'Segunda División',
    code: 'SD',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 636,
      startDate: '2020-09-13',
      endDate: '2021-06-15',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 9,
    lastUpdated: '2020-10-05T03:55:09Z',
  },
  {
    id: 2014,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg',
    },
    name: 'Primera Division',
    code: 'PD',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 635,
      startDate: '2020-09-13',
      endDate: '2021-05-23',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 28,
    lastUpdated: '2020-10-05T04:11:18Z',
  },
  {
    id: 2078,
    area: {
      id: 2224,
      name: 'Spain',
      countryCode: 'ESP',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg',
    },
    name: 'Supercopa de España',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 510,
      startDate: '2020-01-08',
      endDate: '2020-01-12',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-01-13T10:40:04Z',
  },
  {
    id: 2074,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg',
    },
    name: 'Superettan',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 572,
      startDate: '2020-04-05',
      endDate: '2020-11-07',
      currentMatchday: 21,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:59:43Z',
  },
  {
    id: 2073,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg',
    },
    name: 'Allsvenskan',
    code: 'ALL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 573,
      startDate: '2020-04-05',
      endDate: '2020-12-06',
      currentMatchday: 23,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T03:13:32Z',
  },
  {
    id: 2075,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg',
    },
    name: 'Playoffs 2/3',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 79,
      startDate: '2017-11-08',
      endDate: '2017-11-11',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:28:43Z',
  },
  {
    id: 2076,
    area: {
      id: 2233,
      name: 'Sweden',
      countryCode: 'SWE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 80,
      startDate: '2017-11-15',
      endDate: '2017-11-19',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-05T00:28:54Z',
  },
  {
    id: 2071,
    area: {
      id: 2234,
      name: 'Switzerland',
      countryCode: 'CHE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg',
    },
    name: 'Schweizer Pokal',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 489,
      startDate: '2019-08-20',
      endDate: '2020-08-30',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:00:46Z',
  },
  {
    id: 2072,
    area: {
      id: 2234,
      name: 'Switzerland',
      countryCode: 'CHE',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg',
    },
    name: 'Super League',
    code: 'SSL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 488,
      startDate: '2019-07-20',
      endDate: '2020-08-02',
      currentMatchday: 36,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:00:39Z',
  },
  {
    id: 2068,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg',
    },
    name: '1. Lig',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 545,
      startDate: '2019-08-18',
      endDate: '2020-07-19',
      currentMatchday: 34,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:00:30Z',
  },
  {
    id: 2070,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg',
    },
    name: 'Süper Lig',
    code: 'TSL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 637,
      startDate: '2020-09-11',
      endDate: '2021-05-16',
      currentMatchday: 4,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T03:28:32Z',
  },
  {
    id: 2069,
    area: {
      id: 2247,
      name: 'Turkey',
      countryCode: 'TUR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg',
    },
    name: 'TFF Süper Kupa',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 511,
      startDate: '2019-08-07',
      endDate: '2019-08-07',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2019-08-07T21:11:21Z',
  },
  {
    id: 2065,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg',
    },
    name: 'Kubok Ukrainy',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 551,
      startDate: '2019-08-07',
      endDate: '2020-07-08',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T14:00:09Z',
  },
  {
    id: 2064,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg',
    },
    name: 'Premier Liha',
    code: 'UPL',
    emblemUrl: null,
    plan: 'TIER_THREE',
    currentSeason: {
      id: 625,
      startDate: '2020-08-21',
      endDate: '2021-05-30',
      currentMatchday: 5,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2020-10-05T03:36:54Z',
  },
  {
    id: 2066,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg',
    },
    name: 'Playoffs 1/2',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 70,
      startDate: '2018-05-23',
      endDate: '2018-05-27',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2018-06-02T14:03:07Z',
  },
  {
    id: 2067,
    area: {
      id: 2253,
      name: 'Ukraine',
      countryCode: 'UKR',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg',
    },
    name: 'Superkubok Ukrainy',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 648,
      startDate: '2020-08-25',
      endDate: '2020-08-25',
      currentMatchday: null,
      winner: null,
    },
    numberOfAvailableSeasons: 4,
    lastUpdated: '2019-07-28T23:59:39Z',
  },
  {
    id: 2145,
    area: {
      id: 2256,
      name: 'United States',
      countryCode: 'USA',
      ensignUrl: null,
    },
    name: 'MLS',
    code: 'MLS',
    emblemUrl: null,
    plan: 'TIER_TWO',
    currentSeason: {
      id: 571,
      startDate: '2020-02-29',
      endDate: '2020-11-10',
      currentMatchday: 3,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T11:00:21Z',
  },
  {
    id: 2063,
    area: {
      id: 2257,
      name: 'Uruguay',
      countryCode: 'URY',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 588,
      startDate: '2020-02-15',
      endDate: '2020-11-28',
      currentMatchday: 14,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-05T05:00:22Z',
  },
  {
    id: 2148,
    area: {
      id: 2257,
      name: 'Uruguay',
      countryCode: 'URY',
      ensignUrl: null,
    },
    name: 'Supercopa Uruguaya',
    code: 'SUCU',
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 569,
      startDate: '2020-02-01',
      endDate: '2020-02-01',
      currentMatchday: 1,
      winner: null,
    },
    numberOfAvailableSeasons: 1,
    lastUpdated: '2020-01-30T10:47:26Z',
  },
  {
    id: 2062,
    area: {
      id: 2262,
      name: 'Venezuela',
      countryCode: 'VEN',
      ensignUrl: null,
    },
    name: 'Primera División',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 566,
      startDate: '2020-01-26',
      endDate: '2020-12-12',
      currentMatchday: 33,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:59:30Z',
  },
  {
    id: 2061,
    area: {
      id: 2263,
      name: 'Vietnam',
      countryCode: 'VIE',
      ensignUrl: null,
    },
    name: 'V-League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 570,
      startDate: '2020-02-22',
      endDate: '2020-11-04',
      currentMatchday: 13,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-10-02T06:00:08Z',
  },
  {
    id: 2060,
    area: {
      id: 2264,
      name: 'Wales',
      countryCode: 'WAL',
      ensignUrl:
        'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Wales_%281959%E2%80%93present%29.svg',
    },
    name: 'Welsh Premier League',
    code: null,
    emblemUrl: null,
    plan: 'TIER_FOUR',
    currentSeason: {
      id: 518,
      startDate: '2019-08-16',
      endDate: '2020-05-30',
      currentMatchday: 22,
      winner: null,
    },
    numberOfAvailableSeasons: 3,
    lastUpdated: '2020-09-10T13:59:11Z',
  },
  {
    id: 2000,
    area: {
      id: 2267,
      name: 'World',
      countryCode: 'INT',
      ensignUrl: null,
    },
    name: 'FIFA World Cup',
    code: 'WC',
    emblemUrl: null,
    plan: 'TIER_ONE',
    currentSeason: {
      id: 1,
      startDate: '2018-06-14',
      endDate: '2018-07-15',
      currentMatchday: 3,
      winner: {
        id: 773,
        name: 'France',
        shortName: 'France',
        tla: 'FRA',
        crestUrl: 'https://crests.football-data.org/773.svg',
      },
    },
    numberOfAvailableSeasons: 2,
    lastUpdated: '2020-09-10T13:58:14Z',
  },
];

export default competitions;
